### ISSUE TITLE
LH/RH in make_distance_matrix.m

### ISSUE THREAD

**Issue by droediger** [cjl2007/PFM-Depression#1]
Looks like there's a naming collision that breaks the make_distance_matrix.m script in this repo. The gifti objects and their associated distance matrices are both assigned the names "LH" / "RH". 

In the Targeted-Functional-Network-Stimulation [version](https://github.com/cjl2007/Targeted-Functional-Network-Stimulation/blob/main/PFM/make_distance_matrix.m#L37-L48) of this script, this was avoided by using lowercase (lh/rh) names for the distance matrices and uppercase for the gifti objects.

**Comment by cjl2007** [comment]
Thank you for catching this, the older version of this script was included by mistake, the "lh/rh" version has been included now.
